# Generated by Django 3.2.1 on 2021-07-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0019_rename_sections_sec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sec',
        ),
    ]
