# Generated by Django 3.2.1 on 2021-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0020_delete_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('attendance', models.CharField(max_length=30)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
