# Generated by Django 3.2.1 on 2021-07-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceRecognition', '0022_alter_attendance_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
